version: 0.2
env:
  variables:
    GOPATH: "/go"
    GOBIN: "/go/bin"

phases:
  install:
    runtime-versions:
      golang: latest

  build:
    commands:
      - make signup
  post_build:
    commands:
      - aws lambda update-function-code --function-name project-signup --zip-file fileb://signup.zip

artifacts:
  files:
    - signup/signup.zip
