version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching commit tag..."
      - export GIT_TAG=$(git describe --tags --abbrev=0 || echo "default-function")  # Get latest tag or fallback
      - export PROJECT_NAME=$(echo $GIT_TAG | cut -d'-' -f1)  # Extract first part before '-'
      - echo "Extracted Project Name: $PROJECT_NAME"
      - echo "PROJECT_NAME=$PROJECT_NAME" >> $CODEBUILD_ENV_FILE  # Persist the variable

  build:
    commands:
      - make $PROJECT_NAME

artifacts:
  files:
    - signup/signup.zip  # Use a static reference to the output file
