version: 0.2

phases:
  install:
    commands:
      - apt install go
      - apt install git
      - apt install make
  pre_build:
    commands:
      - echo "Fetching commit tag..."
      - export GIT_TAG=$(git describe --tags --abbrev=0 || echo "default-function")
      - export PROJECT_NAME=$(echo $GIT_TAG | cut -d'-' -f1)

  build:
    commands:
      - make $PROJECT_NAME

artifacts:
  files:
    - signup/signup.zip
