version: 0.2
env:
  variables:
    GOPATH: "/go"
    GOBIN: "/go/bin"

phases:
  install:
    runtime-versions:
      golang: latest

  build:
    commands:
      - make signup
      - make signin
      - make presignedurl
      - make updateimageurl
  post_build:
    commands:
      - aws lambda update-function-code --function-name FunctionSignup --zip-file fileb://signup.zip
      - aws lambda update-function-code --function-name FunctionSignin --zip-file fileb://signin.zip
      - aws lambda update-function-code --function-name FunctionPresign --zip-file fileb://presign.zip
      - aws lambda update-function-code --function-name FunctionUpdateUrl --zip-file fileb://updateurl.zip

artifacts:
  files:
    - signup.zip
    - signin.zip
    - presign.zip
    - updateurl.zip
