version: 0.2
env:
  variables:
    GOPATH: "/go"
    GOBIN: "/go/bin"

phases:
  install:
    runtime-versions:
      golang: latest

  build:
    commands:
      - make signup

artifacts:
  files:
    - signup/signup.zip
