AWSTemplateFormatVersion: "2010-09-09"
# 1. create a connection to github

# 2. create a buildproject
# 3. create a buildrole
# 4. create a piplineRole
# 5. create a lambda function

Parameters:
  S3BucketName:
    Type: String
    Default: arsinuxbucket

  BuildProjectName:
    Type: String
    Default: projectbuild

  GitHubConnectionArn:
    Type: String
    Default: "arn:aws:codeconnections:us-east-1:098234648102:connection/2a72df8e-08e9-4e8d-914d-167ddaf7cc5b"

  GitHubRepo:
    Type: String
    Default: "ametow/cloud-final-project-backend"

  LambdaFunctionName:
    Type: String
    Default: "triggerCloudFrontUpdate"

  PipelineRole:
    Type: String
    Default: "arn:aws:iam::098234648102:role/service-role/AWSCodePipelineServiceRole-us-east-1-assgn10"

Resources:

  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyPipeline
      RoleArn: !Ref PipelineRole
      ArtifactStore:
        Type: S3
        Location: !Ref S3BucketName
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                BranchName: main

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildProjectName

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                BucketName: !Ref S3BucketName
                Extract: "true"

        - Name: InvokeLambda
          Actions:
            - Name: InvokeLambdaAction
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                FunctionName: !Ref LambdaFunctionName
                UserParameters: !Sub '{"distributionId": "${CloudFrontDistribution}"}'

Outputs:
  PipelineName:
    Value: !Ref MyCodePipeline
    Description: "CodePipeline Name"
# mybuildproject
# role
